// Every user-facing string lives here so the UI can be translated later.
// Voice: calm, plain, specific. See DESIGN.md ("Voice and tone").

import { plural } from "./format";

export const strings = {
  app: {
    name: "Sheltie",
    tagline: "Keeps watch over your homelab",
    skip: "Skip to content",
  },
  nav: {
    overview: "Overview",
    incidents: "Incidents",
    monitors: "Monitors",
    containers: "Containers",
    network: "Network",
    host: "Host",
    settings: "Settings",
    more: "More",
    docs: "Documentation",
    star: "Star on GitHub",
  },
  connection: {
    live: "Live",
    connecting: "Connecting…",
    stale: "Updates delayed",
    offline: "Can't reach Sheltie",
    demo: "Demo data",
    updated: (age: string) => `Updated ${age}`,
    offlineBanner: (age: string) => `Sheltie isn't responding. Showing the last known state from ${age}. Retrying automatically.`,
    neverBanner: "Can't reach the Sheltie API. Check that the container is running, then retry.",
    retry: "Retry now",
  },
  search: {
    trigger: "Search or run a command",
    placeholder: "Type a command or search monitors and containers…",
    empty: "No matches. Try a page name, monitor or container.",
    groups: { pages: "Go to", actions: "Actions", monitors: "Monitors", containers: "Containers" },
  },
  status: {
    allGood: "All systems normal",
    problems: (count: number) => (count === 1 ? "1 problem needs attention" : `${count} problems need attention`),
    checks: (count: number) => `${plural(count, "check")} healthy`,
    lastIncident: (age: string) => `last incident ${age}`,
    noIncidents: "no incidents recorded",
    silencedUntil: (time: string) => `Alerts silenced until ${time}`,
    silenced: "Alerts silenced until you resume them",
    up: "Up",
    down: "Down",
    unknown: "Unknown",
    running: "Running",
    stopped: "Stopped",
  },
  silence: {
    button: "Alerts on",
    silencedButton: "Silenced",
    oneHour: "Silence for 1 hour",
    fourHours: "Silence for 4 hours",
    untilResumed: "Silence until I resume",
    resume: "Resume alerts",
    done: "Alerts silenced",
    resumed: "Alerts resumed",
  },
  overview: {
    eyebrow: "Overview",
    sinceVisit: "Since your last visit",
    sinceVisitEmpty: (age: string) => `Nothing happened since you were last here ${age}.`,
    sinceVisitSummary: (count: number, away: string) => `${plural(count, "event")} while you were away (${away})`,
    recentActivity: "Recent activity",
    viewAll: "View all incidents",
    attention: "Needs attention",
    attentionEmpty: "Nothing needs your attention right now.",
    vitals: "Vital signs",
    pinned: "Pinned monitors",
    pinnedHint: "Pin monitors in Settings to choose what appears here.",
    setup: "Finish setting up Sheltie",
    setupProgress: (done: number, total: number) => `${done} of ${total} done`,
    setupSteps: {
      monitor: "Add your first website monitor",
      telegram: "Connect Telegram for alerts on your phone",
      token: "Save the action token so you can fix things from here",
      notify: "Turn on desktop notifications",
    },
  },
  incidents: {
    eyebrow: "Incidents",
    headline: (count: number) => (count ? `${plural(count, "event")} recorded` : "No incidents recorded"),
    meta: "Alerts, recoveries, repairs and Docker events, newest first.",
    search: "Search incidents",
    all: "All",
    problems: "Problems",
    recoveries: "Recoveries",
    repairs: "Repairs",
    clear: "Clear history",
    clearTitle: "Clear incident history?",
    clearBody: "This deletes every recorded event from history.db. Active alerts keep running.",
    empty: "No incidents match these filters.",
  },
  monitors: {
    eyebrow: "Monitors",
    headline: (up: number, total: number) => (total ? `${up} of ${total} sites up` : "No website monitors yet"),
    add: "Add monitor",
    search: "Search monitors",
    filterAll: "All",
    filterDown: "Down",
    filterUp: "Up",
    empty: "No monitors yet",
    emptyBody: "Paste the address of a website or service and Sheltie checks it every cycle.",
    noMatch: "No monitors match.",
    select: "Select a monitor to see its history.",
    response: "Response",
    average: "Average",
    p95: "95th percentile",
    uptime: "Uptime",
    lastChecks: (count: number) => `Last ${plural(count, "check")}`,
    responseTime: "Response time",
    open: "Open site",
    remove: "Remove",
    removeTitle: (name: string) => `Remove ${name}?`,
    removeBody: "Sheltie stops checking this site. Monitors defined in config.yml come back on restart.",
    removed: (name: string) => `${name} removed`,
    undo: "Undo",
    lastError: "Last error",
    statusCode: "HTTP status",
    form: {
      title: "Add a monitor",
      url: "Address",
      urlHint: "Paste a full address, for example https://nextcloud.home.lan",
      urlError: "Enter an address that starts with http:// or https://",
      name: "Name",
      nameHint: "Shown in alerts. We suggest one from the address.",
      advanced: "Advanced options",
      expected: "Expected status codes",
      expectedHint: "Comma separated, for example 200, 301",
      keyword: "Must contain text (optional)",
      keywordHint: "The site counts as down if this text is missing.",
      timeout: "Timeout (seconds)",
      submit: "Start monitoring",
      cancel: "Cancel",
      added: (name: string) => `Monitoring ${name}`,
    },
  },
  containers: {
    eyebrow: "Containers",
    headline: (running: number, total: number) => (total ? `${running} of ${total} containers running` : "No containers found"),
    unavailable: "Docker isn't reachable",
    unavailableBody: "Mount /var/run/docker.sock into the Sheltie container to see containers here.",
    search: "Search containers",
    all: "All",
    running: "Running",
    stopped: "Stopped",
    restart: "Restart",
    start: "Start",
    restartTitle: (name: string) => `Restart ${name}?`,
    restartBody: "The container stops and starts again. Anything it is serving is briefly unavailable.",
    blocked: "Protected in actions.blocked_containers",
    protected: "Protected",
    watching: (count: number) => `Auto-heal watches ${plural(count, "container")}`,
    userStopped: "Stopped on purpose",
    tracked: "Auto-heal watching",
    empty: "No containers match.",
  },
  network: {
    eyebrow: "Network",
    path: "Connection path",
    host: "This server",
    route: "Default route",
    internet: "Internet",
    interfaces: "Interfaces",
    state: "State",
    carrier: "Cable / link",
    ipv4: "IPv4 address",
    yes: "Yes",
    no: "No",
    headlineOk: "Online",
    headlineDown: "Internet is unreachable",
    headlineUnknown: "Checking the connection…",
    viaRoute: (label: string) => `Traffic leaves through ${label}`,
    noInterfaces: "No interfaces configured. Add network.ethernet or network.wifi to config.yml.",
  },
  host: {
    eyebrow: "Host",
    headlineOk: "Host is healthy",
    headlineBusy: (what: string) => `${what} is running high`,
    cpu: "CPU",
    ram: "Memory",
    disk: "Disk",
    temp: "CPU temperature",
    load: "Load average",
    loadHint: "1, 5 and 15 minutes",
    trend: "Live trend since you opened Sheltie",
    clearCache: "Clear RAM cache",
    clearCacheTitle: "Clear the Linux page cache?",
    clearCacheBody: "This drops cached files from memory. It is safe, but disks are busier for a while as the cache refills.",
    unavailable: "Unavailable",
  },
  settings: {
    eyebrow: "Settings",
    headline: "Preferences",
    meta: "Stored in this browser only.",
    appearance: "Appearance",
    theme: "Theme",
    system: "System",
    light: "Light",
    dark: "Dark",
    refresh: "Refresh every",
    notifications: "Notifications",
    popups: "Show alert pop-ups in Sheltie",
    desktop: "Desktop notifications",
    desktopHint: "Get a system notification for new problems while this tab is open.",
    enable: "Enable",
    enabled: "Enabled",
    blocked: "Blocked by the browser",
    token: "Action token",
    tokenHint: "Needed to restart containers, add monitors and silence alerts. Find it with: docker logs sheltie | grep token",
    tokenSave: "Save token",
    tokenSaved: "Token saved in this browser",
    tokenCleared: "Token cleared",
    pins: "Pinned on Overview",
    pinsHint: "Choose the monitors shown on the Overview page.",
    shortcuts: "Keyboard shortcuts",
    about: "About",
    version: "Version",
    started: "Running since",
    telegram: "Telegram alerts",
    connected: "Connected",
    notConnected: "Not connected",
  },
  actions: {
    confirm: "Confirm",
    cancel: "Cancel",
    close: "Close",
    failed: "That didn't work",
    done: "Done",
    tokenTitle: "Action token needed",
    tokenBody: "Sheltie protects actions with a token. Paste it below. It was printed when Sheltie first started:",
    tokenCommand: "docker logs sheltie 2>&1 | grep -i token",
    tokenSubmit: "Save and retry",
  },
  shortcuts: {
    title: "Keyboard shortcuts",
    palette: "Open search and commands",
    help: "Show this help",
    goto: (page: string) => `Go to ${page}`,
  },
  problems: {
    siteDown: (name: string) => `${name} is down`,
    siteDownBody: (detail: string) => detail,
    internetDown: "Internet is unreachable",
    internetDownBody: "Every probe host failed. Check the router or your ISP.",
    cpuHigh: "CPU is running high",
    ramHigh: "Memory is almost full",
    diskHigh: (path: string) => `Disk ${path} is almost full`,
    tempHigh: "CPU is running hot",
    containerStopped: (name: string) => `${name} has stopped`,
    containerStoppedBody: (status: string) => `Status: ${status}. It was running before, so this is probably not intended.`,
    interfaceDown: (label: string) => `${label} is disconnected`,
    generic: (id: string) => id.replace(/[._]/g, " "),
    viewHost: "View host",
    viewNetwork: "View network",
    viewMonitor: "View monitor",
    viewIncidents: "View incidents",
    openSite: "Open site",
  },
};

export type Strings = typeof strings;
